### PR TITLE
Get Travis build working (try using Stack instead of Cabal)

### PR DESCRIPTION
**Pull request by lassik**
Here's an alternative take, Stack has official Travis instructions at https://docs.haskellstack.org/en/stable/travis_ci/

### CODE REVIEW

**Comment by lassik** [comment]
Okay, this now works! 😄  But... the beautifier output doesn't match the text fixture. According to the Travis log, it seems to have some extra whitespace and I can't figure out why.

**Comment by stevenzeck** [comment]
@lassik I took the raw original and formatted it at https://hexagoxel.de/brittany/ and it matches what Travis has.  Maybe you have a different version of brittany locally?

MacOS is also failing because it can't install Haskell Stack.

**Comment by lassik** [comment]
Hey, I had no idea they have a web version :) You're right, I had an old version of Brittany on my computer. Can't figure out how to get Stack to upgrade or uninstall it either. The Haskell folks are not kidding with their slogan to "avoid success at all costs"! But I updated the fixture by hand...

**Comment by lassik** [comment]
It now works. But builds are taking 30-60 minutes! The last one timed out. There was some NPM update ongoing in the one that timed out.

**Comment by lassik** [comment]
@Glavin001 or @stevenzeck Can you restart the build from the Travis UI?

**Comment by stevenzeck** [comment]
I restarted it.  `brew install haskell-stack` might be a better option for Mac to install stack.

**Comment by lassik** [comment]
`brew` would indeed be more idiomatic/maybe faster on the Mac, but Linux doesn't have it, so our Travis file would get more convoluted with if-statements and the like. The current Travis config works identically for Mac and Linux with no if-statements.

**Pull request merged**
